- hosts: web
  become: true
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: present
      update_cache: yes
      
  - name: Install a list of packages
    apt:
      pkg:
      - unzip

  - name: start apache2 service
    ansible.builtin.service: 
      name: apache2
      state: started
      enabled: yes
  
  - name: Download tooplate.com
    get_url:
      url: https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip
      dest: /home/ubuntu

  - name: Extract 
    ansible.builtin.unarchive:
      src: /home/ubuntu/2119_gymso_fitness.zip
      dest: /tmp/
      remote_src: yes
      
  - name: Copy a "sudoers" file on the remote machine for editing
    copy:
      src: /home/ubuntu/tmp/2119_gymso_fitness/*
      dest: /var/www/html/
      remote_src: yes
