- hosts: 172.31.89.106
  gather_facts: false
  become: true
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: present
      update_cache: yes

  - name: start apache2 service
    service: 
      name: apache2
      state: started
      enabled: yes
      
  - name: deploy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html 
